### ISSUE TITLE
Move to text based configuration

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/collector-sidecar#201]
### Problem description
Currently the web interface offers an abstracted view of the collector configuration to the user. The intention was to provide a simple interface to the user so that without much domain knowledge a configuration is possible. While this is ok for new users, advanced users feel kind of blocked by this approach. At the same time it puts some workload on the maintainers to add more configuration flags.
We want to change this to a more powerful approach where users have access to the full configuration.

### Proposed changes

  * Remove the current abstraction layer
  * Design a text based configuration view
  * Implement a text based configuration based on templates, like the 'Snippets' we have today.

### Implementation

  - [ ] Current modal view should be replaced by configuration page
  - [ ] A snippet editor should be the main way of creating configurations
  - [ ] Additional help/wizard is provided to the user
  - [ ] Tag management page should exist
  - [ ] The sidecar provides automated host tags like `Linux` or `Windows`
  - [ ] Snippets should be version-controlled
  - [ ] Collector properties like binary path, how to execute and validate should be configured in the Java part and maybe pluggable
  - [ ] Additional content like collector filter rules should be supported by content-packs
  - [ ] Communication should be secured by API tokens
